

title: SW Study


# Markdown settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  mathjax:
    path: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'

highlighter: rouge


# Build settings
theme: minima


url: "https://fy-create.github.io"
#baseurl: "/tutorialforC"
baseurl: ""

